### PR TITLE
EASY-1620: adjust color scheme to use DANS/EASY colors

### PR DESCRIPTION
**Pull request by rvanheest**
Fixes EASY-1620

#### When applied it will
* use the DANS colors in the deposit ui

@DANS-KNAW/easy for review

**Login screen:**
image

**Deposit overview:**
image

**Hover on delete button at deposit overview:**
image

**Deposit form with links to help texts:**
image

**Deposit form with hovered link to help texts:**
image

**Deposit form with enabled and disabled 'add' and 'remove' buttons:**
image

**Deposit form with hovered 'add' button:**
image

**Deposit form with hovered 'remove' button:**
image

**Deposit form with 'normal', 'disabled' and 'hovered' validate button:**
image

**Deposit form with opened and closed tabs (arrows):**
image

### CODE REVIEW

**Comment by rvanheest** [comment]
after looking at the results of this PR some more, I really start to dislike the colors @lindareijnhoudt and I have chosen this morning; especially the gray tones on the deposit form with only color on the buttons while hovering. It starts to feel quite dull and boring. We should probably spend some more time, together with other people, to figure out which colors we should use (rather than these gray tones). If I can find some time, I'll try to make some alternatives in the next couple of days.

**Comment by janvanmansum** [comment]
I think it looks great! As programmers we shouldn't concern ourselves too much with the style of the application. Currently we have a house style designed by a company that specializes in that sort of thing. We should stick to that style as best as we can.

**Comment by rvanheest** [comment]
@janvanmansum what I meant was not the house style. This only involves the blue card headers and red stars in the images above. These look just fine.

What I'm hesitating about is the gray colors in the images above, which are _not_ part of the house style. We made them up ourselfs. I'll post some other images later about how it looked before @lindareijnhoudt and I made the last 5 commits.

**Comment by rvanheest** [comment]
I made some final changes; mainly semantic color names. As discussed offline with @janvanmansum would should probably ask some external advice on the usage of color in the validate, remove and add buttons. I'll send an email about that later today.

**Pull request merged**
